name: Build & Deploy Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

env:
  PROJECT_NAME: portifolio
  CI: false

jobs:
  build:
    name: build & deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: node install && build
        shell: bash
        run: |-
          npm install

      - name: react install && build
        shell: bash
        run: |-
          cd ./view
          npm install && npm run build
          cp -r build ../
          cd ../

      - name: deleting development files
        shell: bash
        run: |-
          rm -r ./node_modules
          rm -r ./view
          echo 'mostrando arquivos que serão enviados ao app engine'
      
      - name: Deploy Dev
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          credentials: ${{ secrets.GCLOUD_SA_KEY}}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID}}
          promote: true
          version: ${{ github.run_number}}-${{ github.run_id }}-development
