name: Build & Deploy Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

env:
  PROJECT_NAME: portifolio
  CI: false

jobs:
  build:
    name: build & deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Installation of dependencies
        shell: bash
        run: |-
          npm install

      - name: generating build files
        shell: bash
        run: |-
          npm run build
      
      - name: Deploy Dev
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          credentials: ${{ secrets.GCLOUD_SA_KEY}}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID}}
          promote: true
          version: ${{ github.run_number}}-${{ github.run_id }}-development
